"""Core domain package for Arquivabilidade JA."""

from archivability.evidence import (
    Evidence,
    EvidenceSource,
    EvidenceValidationError,
    HttpMetadataDerivation,
    HttpMetadataDerivationError,
    Observation,
    derive_indicator_result,
    derive_http_metadata_indicators,
)
from archivability.lifecycle import (
    Analysis,
    AnalysisOrchestrator,
    AnalysisState,
    Attempt,
    AttemptState,
    LifecycleError,
)
from archivability.methodology.loader import load_methodology
from archivability.methodology.models import (
    AssessmentResult,
    IndicatorResult,
    LegacyClearPlusInput,
    MethodologyConfig,
    ResultState,
)
from archivability.methodology.scoring import ScoringEngine
from archivability.probes import (
    AddressResolver,
    ApprovedTarget,
    Probe,
    ProbeContext,
    ProbeExecutionOutcome,
    ProbeExecutionRepository,
    ProbeExecutionService,
    ProbeRequest,
    ProbeRequestAuthorizer,
    ProbeRunResult,
    ProbeRunner,
    ProbeValidationError,
    SsrfPolicy,
)
from archivability.storage import (
    AuditContext,
    ConcurrencyConflict,
    DuplicateRecordError,
    IntegrityViolation,
    PersistenceError,
    SqliteEvidenceRepository,
    SqliteLifecycleRepository,
    apply_sqlite_migrations,
    configure_sqlite_connection,
)

__all__ = [
    "AssessmentResult",
    "Analysis",
    "AnalysisOrchestrator",
    "AnalysisState",
    "AddressResolver",
    "AuditContext",
    "Attempt",
    "AttemptState",
    "ApprovedTarget",
    "ConcurrencyConflict",
    "DuplicateRecordError",
    "Evidence",
    "EvidenceSource",
    "EvidenceValidationError",
    "HttpMetadataDerivation",
    "HttpMetadataDerivationError",
    "IndicatorResult",
    "IntegrityViolation",
    "LegacyClearPlusInput",
    "LifecycleError",
    "MethodologyConfig",
    "Observation",
    "PersistenceError",
    "Probe",
    "ProbeContext",
    "ProbeExecutionOutcome",
    "ProbeExecutionRepository",
    "ProbeExecutionService",
    "ProbeRequest",
    "ProbeRequestAuthorizer",
    "ProbeRunResult",
    "ProbeRunner",
    "ProbeValidationError",
    "ResultState",
    "ScoringEngine",
    "SqliteEvidenceRepository",
    "SqliteLifecycleRepository",
    "SsrfPolicy",
    "apply_sqlite_migrations",
    "configure_sqlite_connection",
    "derive_indicator_result",
    "derive_http_metadata_indicators",
    "load_methodology",
]
